misPerris/urls.py
from django.urls import path
#para cargar y mostrar imagenes en otro lugar que no
#sea assets, cosas de BD se guardan aparte
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    #regular page
    path("", views.index, name="index"),
    path("about-us/", views.about_view, name="about-us"),
    path("contact/", views.contact_view, name="contact"),
    path("rescatados/", views.rescatados_view, name="rescatados"),

    #users
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name="login"),
    path('register/', views.register_view, name="register"),
    #path('acceso-denegado/', views.admin_view, name="check"),
    path('reset-password/', views.password_reset_request, name='password_reset_request'),
    path('reset-password/<str:uid>/<str:token>/', views.password_reset, name='password_reset'),     
    #animal
    path('animal-detail/<int:animal_id>', views.animal_detail, name="animal-detail"),
    path('solicitar/<int:animal_id>', views.make_solicitud, name="solicitar"),

    #users admin
    path("panel/", views.admin_view, name="panel"),
    path("panel/agregar", views.animal_create, name="agregar"),
    path("panel/editar/<int:animal_id>", views.animal_edit, name="editar"),
    path("panel/eliminar/<int:animal_id>", views.animal_delete, name="eliminar"),
    # vista para cargar datos de region y ciudad a BBDD 
    #path('cargar_datos_desde_json/', views.cargar_datos_desde_json, name='cargar_datos_desde_json'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

misPerris2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("misPerris.urls")),
]

misPerris/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Region(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Ciudad(models.Model):
    nombre = models.CharField(max_length=100)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, related_name='region')

    def __str__(self):
        return self.nombre


class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, blank=True)
    city = models.ForeignKey(Ciudad, on_delete=models.SET_NULL, null=True, blank=True)

    

    USERNAME_FIELD = 'username'  
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name', 'region', 'city'] 

    def __str__(self):
        return self.username
    
class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    rut = models.CharField(max_length=10)
    date_of_birth = models.DateField()
    phone = models.CharField(max_length=20)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, related_name='region_nombre')
    city = models.ForeignKey(Ciudad, on_delete=models.CASCADE, related_name='ciudad_nombre')
    housing_type = models.CharField(max_length=100)
    terms = models.BooleanField()
    timestamp = models.DateTimeField(auto_now_add=True)
    message = models.CharField(max_length=250, default='')

    def __str__(self):
        return self.name
    
class Animal(models.Model):
    ESTADO_CHOICES = (
        ('rescatado', 'Rescatado'),
        ('disponible', 'Disponible'),
        ('adoptado', 'Adoptado'),
    )

    SIZE_CHOICES = (
        ('pequeno', 'Pequeño'),
        ('mediano', 'Mediano'),
        ('grande', 'Grande')
    )

    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='animal_images')
    raza = models.CharField(max_length=100)
    size = models.CharField(max_length=50, choices=SIZE_CHOICES)
    peso = models.CharField(max_length=10)
    descripcion = models.TextField()
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES)


    def __str__(self):
        return self.nombre
    
class Solicitud(models.Model):
    ESTADO_CHOICES = (
        ('Pendiente', 'Pendiente'),
        ('Aprobada', 'Aprobada'),
        ('Rechazada', 'Rechazada'),
    )
    
    id = models.AutoField(primary_key=True)
    animal = models.ForeignKey(Animal, on_delete=models.SET_NULL, null=True, blank=True, related_name='solicitudes')
    usuario = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True, related_name='user_solicitudes')
    estado = models.CharField(max_length=20, choices=ESTADO_CHOICES, default='Pendiente')

    def __str__(self):
        return f"Solicitud #{self.id} - {self.usuario}"

misPerris/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

#manipulacion de archivos
import os

#expresiones regulares
import re

#login - logout - admin
from django.contrib.auth.decorators import user_passes_test, login_required
from django.utils.decorators import method_decorator
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

#models - forms
from .models import Region, Ciudad, Contact, Animal, CustomUser, Solicitud
from .forms import ContactForm, AnimalForm, CustomUserCreationForm
import json


#pasword reset 
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.shortcuts import render
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str 
from django.template.loader import get_template
from django.template import Context
from .utils import TemplateEmail

from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes


def password_reset_request(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        
        try:
            user = CustomUser.objects.get(email=email)
        except CustomUser.DoesNotExist:
            user = None

        if user is not None:
            
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            token = default_token_generator.make_token(user)

       
            current_site = get_current_site(request)
            reset_link = f"{current_site}/reset-password/{uid}/{token}"

           
            email_context = {
                'user': user,
                'reset_link': reset_link
            }
    
            template = TemplateEmail(
                to=email,
                subject='Restablecimiento de contraseña',
                template='reset_password_email',
                context=email_context
            )

            template.fail_silently = False
            template.send()

            return render(request, 'password_reset/password_reset_success.html', {'success': True})
        else:
            return render(request, 'password_reset/password_reset_request.html', {'error': True, 'message': "Correo ingresado no existe, intente de nuevo"})

    return render(request, 'password_reset/password_reset_request.html')


def password_reset(request, uid, token):
    try:
        uid = force_str(urlsafe_base64_decode(uid))
        user = CustomUser.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if request.method == 'POST':
            password = request.POST.get('password')
            confirm_password = request.POST.get('confirm_password')

            if password == confirm_password:
                if not re.search(r'^(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_\-+=]).*$', password):
                    return render(request, 'password_reset/password_reset.html', {'error': True, 'message': 'La contraseña no cumple los requisitos de seguridad.'})
                # Establecer la nueva contraseña para el usuario
                user.set_password(password)
                user.save()

                return render(request, 'password_reset/password_reset_success.html', {'message':'Su contraseña se ha reestablecido satisfactoriamente.'})
            else:
                return render(request, 'password_reset/password_reset.html', {'error': True, 'message': 'Las contraseñas deben coincidir.'})

        return render(request, 'password_reset/password_reset.html')
    else:
        return render(request, 'password_reset/password_reset_invalid.html')

#vista admin ( list animal )
@login_required
def admin_view(request):
    if request.user is not None:
        if(request.user.is_superuser):
            animales = Animal.objects.all()
            form = AnimalForm()
            context = {'animales': animales, 'form': form}
            return render(request, 'admin/panel.html', context)
        else:
            return render(request, 'users/acceso_denegado.html')
    else:
        return render(request, 'users/acceso_denegado.html')

def about_view(request):
    return render(request, 'about-us.html')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                if(user.is_superuser):
                    return redirect('panel')
                else:
                    return redirect('index')
    else:
        form = AuthenticationForm()

    return render(request, 'users/login.html', {'form': form})

def register_view(request):
    if request.method == 'POST':
        #form = UserCreationForm(request.POST)
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                if(user.is_superuser):
                    return redirect('panel')
                else:
                    return redirect('index')
    else:
        #form = UserCreationForm()
        form = CustomUserCreationForm()
    return render(request, 'users/register.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('index')

def index(request):
    animales = Animal.objects.filter(estado='disponible').order_by('id')

    #rangos para galeria principal
    rango1 = animales[:3]
    rango2 = animales[3:5]
    rango3 = animales[5:7]
    rangos = [rango1, rango2, rango3]

    context = {
        'rangos' : rangos
    }

    return render(request, 'index.html', context)

##carga datos de json a base de datos ( basicamente un seeder )
def cargar_datos_desde_json(request):
    with open('misPerris/assets/data.json', encoding='utf-8') as file:
        data = json.load(file)

        for region_data in data['regiones']:
            region = Region.objects.create(nombre=region_data['region'])

            for ciudad_data in region_data['comunas']:
                Ciudad.objects.create(nombre=ciudad_data, region=region)

    return HttpResponse('datos cargados')

def contact_view(request):
    form = ContactForm(request.POST or None)
   
    if form.is_valid():
        # Crear una nueva instancia de Contact y guardar los datos del formulario en ella
        name=form.cleaned_data['name']
        email=form.cleaned_data['email']
        rut=form.cleaned_data['rut']
        date_of_birth=form.cleaned_data['date_of_birth']
        phone=form.cleaned_data['phone']
        region = Region.objects.filter(id=request.POST['region']).first()
        city=form.cleaned_data['city']
        housing_type=form.cleaned_data['housing_type']
        terms=form.cleaned_data['terms']
        message=form.cleaned_data['message']
            
        contact = Contact(
            name=name,
            email=email,
            rut=rut,
            date_of_birth=date_of_birth,
            phone=phone,
            region=region,
            city=city,
            housing_type=housing_type,
            terms=terms,
            message=message
        )
        contact.save()

        context = {
            'name': name
        }


        # Redirigir a la página de éxito
        return render(request, 'events/success.html', context)
    else:
    # The form is not valid, so you need to correct the errors
        print(form.errors)
    context = {
        'form': form,
    }

    return render(request, 'forms/contact.html', context)

def rescatados_view(request):
    animales = Animal.objects.filter(estado='disponible')
    context = {'animales': animales}
    return render(request, 'animal-list.html', context)

def make_solicitud(request, animal_id):
    animal = get_object_or_404(Animal, id=animal_id)

    if request.method == 'POST':
        usuario = request.user
        solicitud = Solicitud.objects.create(usuario=usuario, animal=animal)
        return redirect('index')
    

def animal_detail(request, animal_id):
    animal = Animal.objects.get(id=animal_id)
    if not (animal):
        return render(request, 'events/acceso_denegado.html')
    else:
        return render(request, 'animals/animal_detail.html', {'animal': animal}) 


#animal crud ( create, edit, delete )
def animal_create(request):
    if request.method == 'POST':
        form = AnimalForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('panel')
    else:
        form = AnimalForm()
    return render(request, 'forms/animal_form.html', {'form': form})

def animal_edit(request, animal_id):
    animal = get_object_or_404(Animal, id=animal_id)

    if request.method == 'POST':
        if request.FILES.get('imagen'):
            if animal.imagen:
                imagen_path = animal.imagen.path
                if os.path.exists(imagen_path):
                    os.remove(imagen_path)

misPerris/templates/forms/animal_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h2 class="text-center">
    {% if '/agregar' in request.path %} 
        Registro de Animal 
    {% elif '/editar' in request.path %} 
        Editar Animal 
    {% endif %} 
</h2>
 <form method="post" enctype="multipart/form-data" class="container flex-column my-4 justify-content-center">
     {% csrf_token %}
        {% if error_message %}
            <p>{{ error_message }}</p>
        {% endif %}
  
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Nombre del Animal</label>
            {% render_field form.nombre class="form-control" autocomplete="off" %}
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Imagen</label>
            {% render_field form.imagen class="form-control" autocomplete="off" %}
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Raza Predominante</label>
            {% render_field form.raza class="form-control" autocomplete="off" %}
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Descripción</label>
            {% render_field form.descripcion class="form-control" autocomplete="off" %}
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Estado</label>
            {% render_field form.estado class="form-control" autocomplete="off" %}
        </div>

        <div class="col-8">
            <button type="submit" class="btn btn-primary mt-3 ">
                {% if '/agregar' in request.path %} 
                    Registrar
                {% elif '/editar' in request.path %} 
                    Editar  
                {% endif %} 
            </button>
            <a role="button" href="/panel/" class="btn btn-primary mt-3 ">Cancelar</a>
        </div>
        
</form>
{% endblock %}

misPerris/templates/forms/contact.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" class="container"  up-submit up-target="form" style="height: 60%;">
        <h3>Formulario de Contacto</h3>
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label mt-1 mb-0" for="name" >{{ form.name.label_tag }}</label>
            {% render_field form.name class="form-control name" autocomplete="off"  %}

            <label class="form-label mt-1 mb-0" for="rut">{{ form.rut.label_tag }}</label>
            {% render_field form.rut class="form-control" autocomplete="off" %}

            <label class="form-label mt-1 mb-0" for="date_of_birth">{{ form.date_of_birth.label_tag }}</label>
            {% render_field form.date_of_birth class="form-control" autocomplete="off" %}

            <label class="form-label mt-1 mb-0" for="email">{{ form.email.label_tag }}</label>
            {% render_field form.email class="form-control" autocomplete="off" %}

            <label class="form-label mt-1 mb-0" for="phone">{{ form.phone.label_tag }}</label>
            {% render_field form.phone class="form-control" autocomplete="off" %}

            <label class="form-label mt-1 mb-0" for="region">{{ form.region.label_tag }}</label>
            {% render_field form.region class="form-control"  up-validate="#id_city" id="region" %}
        
            <label class="form-label mt-1 mb-0" for="id_city">{{ form.city.label_tag }}</label>
            {% render_field form.city class="form-control" autocomplete="off" %}

            <label class="form-label mt-1 mb-0" for="housing_type">{{ form.housing_type.label_tag }}</label>
            {% render_field form.housing_type class="form-control" autocomplete="off" %} 
            
            <label class="form-label mt-1 mb-0" for="message">{{ form.message.label_tag }}</label>
            {% render_field form.message class="form-control" autocomplete="off" %}  
           
            <label class="form-label mt-1 mb-0" for="terms">{{ form.terms.label_tag }}</label>
            {% render_field form.terms class="form-check-input" autocomplete="off" %}

        </div>
        <input type="submit" value="Enviar" class="btn btn-primary mb-3">
    </form>

{% endblock %}